owner: OswaldLabsOpenSource
repo: status
sites:
  - name: Oswald Labs
    url: https://oswaldlabs.com
status-website:
  cname: status.oswaldlabs.com
  logoUrl: https://avatars2.githubusercontent.com/u/21421587?s=200&v=4
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: Oswald Labs Home
      href: https://oswaldlabs.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
